Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.define "server1" do |server|
    server.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "server2" do |server|
    server.vm.network "private_network", ip: "192.168.33.12"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd
  SHELL
end
