Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update
    sudo yum install -y epel-release
    sudo yum install -y ansible
  SHELL
  config.vm.synced_folder "./", "/home/vagrant"
end
